//
//  MapScenePresenter.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol MapScenePresentationLogic {
    func presentLocation(response: MapScene.Location.Response)
    func presentRegion(response: MapScene.Region.Response)
    func presentPlaceLocation(response: MapScene.PlaceLocation.Response)
}

class MapScenePresenter: MapScenePresentationLogic {
    weak var viewController: MapSceneDisplayLogic?

    // MARK: Do something

    func presentLocation(response: MapScene.Location.Response) {
        let viewModel = MapScene.Location.ViewModel(
            location: response.location
        )
        viewController?.displayLocation(viewModel: viewModel)
    }
    
    func presentRegion(response: MapScene.Region.Response) {
        let viewModel = MapScene.Region.ViewModel(region: response.region)
        viewController?.displayRegion(viewModel: viewModel)
    }
    
    func presentPlaceLocation(response: MapScene.PlaceLocation.Response) {
        var annotation: MKPointAnnotation?
        
        if let location = response.location {
            annotation = MKPointAnnotation()
            annotation?.title = "Location"
            annotation?.coordinate = location.coordinate
        }

        let viewModel = MapScene.PlaceLocation.ViewModel(annotation: annotation)
        viewController?.displayPlaceLocation(viewModel: viewModel)
    }
    
}
