//
//  MapSceneModels.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

enum MapScene {
    
  // MARK: Use cases
  
    enum Location {
        struct Request {
            let location: CLLocation
        }
        struct Response {
            let location: CLLocation
        }
        struct ViewModel {
            let location: CLLocation
        }
    }
    
}
