//
//  MapSceneInteractor.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation

protocol MapSceneBusinessLogic {
    func showLocation(request: MapScene.Location.Request)
}

protocol MapSceneDataStore {
    var currentLocation: CLLocation? { get set }
}

class MapSceneInteractor: MapSceneDataStore {
    
    var presenter: MapScenePresentationLogic?
    var worker: MapSceneWorker?
    
    //MARK: DataStore
    var currentLocation: CLLocation? = nil {
        didSet {
            self.doLocation(maybeLocation: currentLocation)
        }
    }

    // MARK: Do stuff
    
    private func doLocation(maybeLocation: CLLocation?) {
        if let location = maybeLocation {
            self.showLocation(request: MapScene.Location.Request(location: location))
        }
    }

}

extension MapSceneInteractor: MapSceneBusinessLogic {
    
    func showLocation(request: MapScene.Location.Request) {
        let response = MapScene.Location.Response(location: request.location)
        presenter?.presentLocation(response: response)
    }

}
