//
//  MapSceneConfigurator.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

class MapSceneConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = MapSceneConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: MapSceneViewController) {
        let interactor = MapSceneInteractor()
        let presenter = MapScenePresenter()
        let router = MapSceneRouter()
        let worker = MapSceneWorker()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        interactor.worker = worker
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
}
