//
//  MapScenePresenter.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MapScenePresentationLogic {
    func presentLocation(response: MapScene.Location.Response)
}

class MapScenePresenter: MapScenePresentationLogic {
    weak var viewController: MapSceneDisplayLogic?

    // MARK: Do something

    func presentLocation(response: MapScene.Location.Response) {
        let viewModel = MapScene.Location.ViewModel(location: response.location)
        viewController?.displayLocation(viewModel: viewModel)
    }
    
}
