//
//  MapSceneModels.swift
//  AR Locations
//
//  Created by Mac on 06.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CoreLocation
import MapKit

enum MapScene {
    
  // MARK: Use cases
  
    enum Location {
        struct Request {
            let location: CLLocation
        }
        struct Response {
            let location: CLLocation
        }
        struct ViewModel {
            let location: CLLocation
        }
    }
    
    enum Region {
        struct Request {
            let region: MKCoordinateRegion
        }
        struct Response {
            let region: MKCoordinateRegion
        }
        struct ViewModel {
            let region: MKCoordinateRegion
        }
    }
    
    enum PlaceLocation {
        struct Request {
        }
        struct Response {
            let location: LocationCoordinate2D?
        }
        struct ViewModel {
            let annotation: CustomLocationAnnotation?
        }
    }
    
    enum LoadLocations {
        struct Request {
        }
        struct Response {
            let locations: [LocationCoordinate2D]?
        }
        struct ViewModel {
            let annotations: [CustomLocationAnnotation]?
        }
    }
    
    enum DeInit {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
    
}
