//
//  ARSceneRouter.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ARSceneRoutingLogic {
    func routeToMapScene()
}

protocol ARSceneDataPassing {
    var dataStore: ARSceneDataStore? { get }
}

class ARSceneRouter: NSObject, ARSceneRoutingLogic, ARSceneDataPassing {
    weak var viewController: ARSceneViewController?
    var dataStore: ARSceneDataStore?

    // MARK: Routing
    func routeToMapScene() {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MapSceneViewController") as! MapSceneViewController
        var destinationDS = destinationVC.router!.dataStore!
        passDataToSomewhere(source: dataStore!, destination: &destinationDS)
        navigateToSomewhere(source: viewController!, destination: destinationVC)
    }

//     MARK: Navigation
    func navigateToSomewhere(source: ARSceneViewController, destination: MapSceneViewController) {
      self.viewController?.navigationController?.pushViewController(destination, animated: true)
    }

//     MARK: Passing data
    func passDataToSomewhere(source: ARSceneDataStore, destination: inout MapSceneDataStore) {
        destination.currentRegion = source.currentRegion
        destination.currentLocation = source.currentLocation
    }
}
