//
//  ARSceneInteractor.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ARSceneBusinessLogic {
    func doSomeLogic(request: ARScene.Something.Request)
}

protocol ARSceneDataStore {
    //var name: String { get set }
}

class ARSceneInteractor: ARSceneDataStore {
    
    var presenter: ARScenePresentationLogic?
    var worker: ARSceneWorker?
    
    //MARK: DataStore
    //var name: String = ""

    // MARK: Do stuff
    
    private func doSomething() {
        let request = ARScene.Something.Request()
        self.doSomeLogic(request: request)
    }

}

extension ARSceneInteractor: ARSceneBusinessLogic {
    
    func doSomeLogic(request: ARScene.Something.Request) {
        worker = ARSceneWorker()
        worker?.doSomeWork()
        
        let response = ARScene.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
