//
//  ARSceneViewController.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import SceneKit
import ARKit

protocol ARSceneDisplayLogic: class {
    func displaySomething(viewModel: ARScene.Something.ViewModel)
}

class ARSceneViewController: UIViewController {
    var interactor: ARSceneBusinessLogic?
    var router: (NSObjectProtocol & ARSceneRoutingLogic & ARSceneDataPassing)?

    @IBOutlet weak var arSceneView: ARSCNView!
    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup
  
    private func setup() {
        
        ARSceneConfigurator.sharedInstance.configure(viewController: self)
        
    }
  
    // MARK: View lifecycle
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        // Run the view's session
        arSceneView.session.run(.makeBaseConfiguration(), options: [.removeExistingAnchors, .resetTracking])
    }
    
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        
        // Pause the view's session
        arSceneView.session.pause()
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        doOnDidLoad()
    }

    // MARK: Do something

    //@IBOutlet weak var nameTextField: UITextField!

    func doOnDidLoad() {
        let request = ARScene.Something.Request()
        interactor?.doSomeLogic(request: request)
    }
    
    private func runAR() {
        // Set the view's delegate
        arSceneView.delegate = self
        
        // Show statistics such as fps and timing information
        arSceneView.showsStatistics = true
        
        
        // Create a new scene
        let scene = SCNScene(named: "art.scnassets/ship.scn")!
        
        // Set the scene to the view
        arSceneView.scene = scene
        arSceneView.debugOptions = [ARSCNDebugOptions.showFeaturePoints, ARSCNDebugOptions.showWorldOrigin]
        arSceneView.autoenablesDefaultLighting = true
        arSceneView.session.delegate = self
    }
  
 }

extension ARSceneViewController: ARSceneDisplayLogic {
    
    func displaySomething(viewModel: ARScene.Something.ViewModel) {
        self.runAR()
    }

}

private extension ARConfiguration {
    static func makeBaseConfiguration() -> ARWorldTrackingConfiguration {
        let configuration = ARWorldTrackingConfiguration()
        
        configuration.isAutoFocusEnabled = true
        configuration.worldAlignment = .gravityAndHeading
        configuration.maximumNumberOfTrackedImages = 4
        //configuration.planeDetection = [ .horizontal, .vertical ]
        
        return configuration
    }
}

extension ARSceneViewController: ARSCNViewDelegate {
    
    // MARK: - ARSCNViewDelegate
    
    /*
     // Override to create and configure nodes for anchors added to the view's session.
     func renderer(_ renderer: SCNSceneRenderer, nodeFor anchor: ARAnchor) -> SCNNode? {
     let node = SCNNode()
     
     return node
     }
     */
    
    func session(_ session: ARSession, didFailWithError error: Error) {
        // Present an error message to the user
        
    }
    
    func sessionWasInterrupted(_ session: ARSession) {
        // Inform the user that the session has been interrupted, for example, by presenting an overlay
        
    }
    
    func sessionInterruptionEnded(_ session: ARSession) {
        // Reset tracking and/or remove existing anchors if consistent tracking is required
        
    }
    
}

extension ARSceneViewController: ARSessionDelegate {
    
    func session(_ session: ARSession, didUpdate frame: ARFrame) {
        // self.delegate?.arCameraManager(didFrameUpdate: frame, for: session)
    }
    
}
