//
//  ARScenePresenter.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ARScenePresentationLogic {
    func presentBackFromMap(response: ARScene.BackFromMap.Response)
    func presentStartAR(response: ARScene.StartAR.Response)
    func presentSaveLocation(response: ARScene.SaveLocation.Response)
}

class ARScenePresenter: ARScenePresentationLogic {
    weak var viewController: ARSceneDisplayLogic?

    // MARK: Do something

    func presentBackFromMap(response: ARScene.BackFromMap.Response) {
        let viewModel = ARScene.BackFromMap.ViewModel()
        viewController?.displayBackFromMap(viewModel: viewModel)
    }
    
    func presentStartAR(response: ARScene.StartAR.Response) {
        let viewModel = ARScene.StartAR.ViewModel()
        viewController?.displayStartAR(viewModel: viewModel)
    }
    
    func presentSaveLocation(response: ARScene.SaveLocation.Response) {
        let viewModel = ARScene.SaveLocation.ViewModel(location: response.location)
        viewController?.displaySaveLocation(viewModel: viewModel)
    }
    
}
