//
//  StartSceneInteractor.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol StartSceneBusinessLogic {
    func doSomeLogic(request: StartScene.Something.Request)
}

protocol StartSceneDataStore {
    //var name: String { get set }
}

class StartSceneInteractor: StartSceneDataStore {
    
    var presenter: StartScenePresentationLogic?
    var worker: StartSceneWorker?
    
    //MARK: DataStore
    //var name: String = ""

    // MARK: Do stuff
    
    private func doSomething() {
        let request = StartScene.Something.Request()
        self.doSomeLogic(request: request)
    }

}

extension StartSceneInteractor: StartSceneBusinessLogic {
    
    func doSomeLogic(request: StartScene.Something.Request) {
        worker = StartSceneWorker()
        worker?.doSomeWork()
        
        let response = StartScene.Something.Response()
        presenter?.presentSomething(response: response)
    }

}
