//
//  StartSceneModels.swift
//  AR Locations
//
//  Created by Mac on 05.07.2019.
//  Copyright (c) 2019 Lammax. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum StartScene {
    
  // MARK: Use cases
  
    enum Something {
        struct Request {
            let someLet: Any?
        }
        struct Response {
            let someLet: Any?
        }
        struct ViewModel {
            let someLet: Any?
        }
    }
    
}
